kind: Service
apiVersion: v1
metadata:
  name: instrument-craft-shop
  labels:
    app: instrument-craft-shop
spec:
  selector:
    app: instrument-craft-shop
  ports:
    - port: 9080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: instrument-craft-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: instrument-craft-shop
        version: v1
    spec:
      containers:
      - name: instrument-craft-shop
        image: docker.sebastian-daschner.com/instrument-craft-shop:1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/
          initialDelaySeconds: 40
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/instrument-craft-shop/resources/health
          initialDelaySeconds: 60
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
